name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_run:
    workflows:
      - Sync article
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "." # default value when not using subfolders
  # BUILD_PATH: subfolder

jobs:
  setup:
    name: Setup
    if: ${{ !(github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure') }}
    runs-on: ubuntu-latest
    outputs:
      origin: ${{ steps.pages.outputs.origin }}
      base_path: ${{ steps.pages.outputs.base_path }}
    steps:
      - name: Setup Pages
        id: pages
        run: |
          origin="https://${{ github.event.repository.owner }}.github.io"

          if [ "${{ github.event.repository.name }}" != ${origin} ]; then
            base_path="/${{ github.event.repository.name }}"
          else
            base_path="/"
          fi

          echo "origin=${origin}" >> $GITHUB_OUTPUT
          echo "base_path=${base_path}" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: setup
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml
    with:
      origin: ${{ needs.setup.outputs.origin }}
      base_path: ${{ needs.setup.outputs.base_path }}

  deploy:
    name: Deploy
    needs: build
    permissions:
      pages: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
